# Databricks notebook source
# MAGIC %md
# MAGIC # rebuild_bronze_liquid_clustering — fix the Phase-2 over-partitioning
# MAGIC
# MAGIC `bronze.market_data_daily` was created 2026-06-21 **`PARTITIONED BY (bar_date)`**
# MAGIC → ~3,901 tiny files for a 98 MB table (one partition per trading day, ~85 rows
# MAGIC each). That over-partitioning is the root cause of slow full-scan queries AND
# MAGIC the per-instrument write fan-out. Fix: rebuild **without partitioning, with
# MAGIC Liquid Clustering `CLUSTER BY (symbol, bar_date)`** — right at 98 MB and at 2k scale.
# MAGIC
# MAGIC **Safety design:**
# MAGIC - The original is **RENAMED to `_old_partitioned` (kept as a backup, NOT dropped)** —
# MAGIC   full rollback until you drop it manually.
# MAGIC - **Guard** aborts if the table uses GENERATED columns / CHECK constraints
# MAGIC   (a plain rebuild would drop those — then do it via edited `SHOW CREATE TABLE`).
# MAGIC - **Row counts verified equal** before the swap.
# MAGIC - Table is 98 MB → the whole thing is seconds. **Run as a JOB or detach after.**
# MAGIC
# MAGIC **What is preserved:** all rows, column names/types/nullability, and the key
# MAGIC TBLPROPERTIES (re-set explicitly below). **Reset (acceptable):** table/column
# MAGIC COMMENTs, column DEFAULT clauses (irrelevant — the writer supplies every column),
# MAGIC and columnMapping name-mode (no longer needed; columns already have final names).

# COMMAND ----------
CAT = "tradeanalytics"
SRC = f"{CAT}.bronze.market_data_daily"
NEW = f"{CAT}.bronze.market_data_daily_clustered"
BAK = f"{CAT}.bronze.market_data_daily_old_partitioned"

# COMMAND ----------
# MAGIC %md
# MAGIC ## 1. Baseline + safety guard (STOP if GENERATED/CHECK present)

# COMMAND ----------
src_count = spark.table(SRC).count()
print("source rows:", src_count)

ddl = spark.sql(f"SHOW CREATE TABLE {SRC}").collect()[0][0]
_hazards = [k for k in ["GENERATED ALWAYS AS", "GENERATED BY DEFAULT", " CHECK ", "CONSTRAINT "]
            if k in ddl.upper()]
if _hazards:
    raise Exception(
        f"ABORT — table uses {_hazards}; a CTAS rebuild would DROP them. "
        f"Rebuild via an edited SHOW CREATE TABLE (swap PARTITIONED BY → CLUSTER BY) "
        f"that preserves those definitions instead.\n\nDDL:\n{ddl}")
print("guard OK — no generated columns / check constraints; safe to CTAS-rebuild.")

# COMMAND ----------
# MAGIC %md
# MAGIC ## 2. Build the clustered copy (CTAS — preserves schema for plain columns)

# COMMAND ----------
spark.sql(f"DROP TABLE IF EXISTS {NEW}")   # idempotent re-run
spark.sql(f"""
    CREATE TABLE {NEW}
    CLUSTER BY (symbol, bar_date)
    AS SELECT * FROM {SRC}
""")

# Restore the properties that matter (appendOnly set LAST, after verification).
spark.sql(f"""
    ALTER TABLE {NEW} SET TBLPROPERTIES (
      'quality'                           = 'bronze',
      'phase'                             = '2',
      'stream'                            = 'daily',
      'delta.enableChangeDataFeed'        = 'true',
      'delta.enableDeletionVectors'       = 'true',
      'delta.autoOptimize.optimizeWrite'  = 'true',
      'delta.autoOptimize.autoCompact'    = 'true',
      'delta.logRetentionDuration'        = 'interval 3650 days',
      'delta.deletedFileRetentionDuration'= 'interval 3650 days'
    )
""")
print("clustered table built + properties restored (appendOnly not yet set).")

# COMMAND ----------
# MAGIC %md
# MAGIC ## 3. Verify BEFORE swapping (counts must match; clustering must be set)

# COMMAND ----------
new_count = spark.table(NEW).count()
detail = spark.sql(f"DESCRIBE DETAIL {NEW}").collect()[0].asDict()
print(f"source rows: {src_count}   new rows: {new_count}   match: {src_count == new_count}")
print(f"clusteringColumns: {detail.get('clusteringColumns')}")
print(f"numFiles: {detail.get('numFiles')}   sizeInBytes: {detail.get('sizeInBytes')}")
assert new_count == src_count, "ROW COUNT MISMATCH — do NOT swap; investigate."
assert (detail.get("clusteringColumns") or []), "clustering not applied — investigate."
print("VERIFIED — safe to swap.")

# COMMAND ----------
# MAGIC %md
# MAGIC ## 4. Atomic-ish swap (original kept as backup, never dropped here)

# COMMAND ----------
spark.sql(f"ALTER TABLE {SRC} RENAME TO {BAK}")   # original → backup
spark.sql(f"ALTER TABLE {NEW} RENAME TO {SRC}")   # clustered → live name
# Re-lock append-only on the now-live table.
spark.sql(f"ALTER TABLE {SRC} SET TBLPROPERTIES ('delta.appendOnly' = 'true')")
print(f"SWAPPED: live {SRC} is now clustered; backup at {BAK}")

# COMMAND ----------
# MAGIC %md
# MAGIC ## 5. Final verification

# COMMAND ----------
display(spark.sql(f"DESCRIBE DETAIL {SRC}"))   # partitionColumns [], clusteringColumns [symbol,bar_date], numFiles small
print("live rows:", spark.table(SRC).count(), "(expect", src_count, ")")
# A full GROUP BY that took ~12 min before should now return in seconds:
display(spark.sql(f"""
    SELECT COUNT(*) AS bars, MIN(bar_date) AS earliest, MAX(bar_date) AS latest,
           COUNT(DISTINCT symbol) AS symbols
    FROM {SRC}
"""))

# COMMAND ----------
# MAGIC %md
# MAGIC ## 6. Cleanup (run manually only after you're confident — this deletes the backup)
# MAGIC ```sql
# MAGIC -- Verify a few days of downstream use first, THEN:
# MAGIC DROP TABLE tradeanalytics.bronze.market_data_daily_old_partitioned;
# MAGIC ```
# MAGIC Also: append-only was re-locked; confirm `delta.appendOnly=true` in the final
# MAGIC DESCRIBE DETAIL above. Update the canonical Phase-2 CREATE DDL to use
# MAGIC `CLUSTER BY (symbol, bar_date)` instead of `PARTITIONED BY (bar_date)` so a
# MAGIC future recreate doesn't reintroduce the partitioning.
